{
 "title": "FluentBit",
 "description": "This is a simple dashboard for Fluent-bit",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "targets": [
    { "expr": "fluentbit_input_records_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fluent-bit input bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(fluentbit_input_bytes_total[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit output bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(fluentbit_output_proc_bytes_total[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit error/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(fluentbit_output_errors_total[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit retries/fails",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(fluentbit_output_retries_total[1m])",
     "legendFormat": "Retries {{ pod }}"
    },
    {
     "expr": "rate(fluentbit_output_retries_failed_total[1m])",
     "legendFormat": "Failed {{ pod }}"
    }
   ]
  }
 ]
}