services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    extra_hosts:
      - "hostmachine:172.20.0.1"
    networks:
      monitoring:
        ipv4_address: "172.20.0.2"
    restart: always
#    ports:
#      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    networks:
      monitoring:
        ipv4_address: "172.20.0.3"
    ports:
     - '80:3000'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

networks:
  monitoring:
    ipam:
      config:
        - subnet: "172.20.0.0/28"
          gateway: "172.20.0.1"
